---
- host: all
  connection: local
  become: yes
       
  taks:    
   - name: Apt update
     command: apt update
    
   - name: Pip install docker-py
     command: pip install docker
     
   - name: Set up the repository
     command: apt install apt-transport-https ca-certificates curl gnupg lsb-release

   - name: Add GPG key
     command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
     
   - name: Add echo
     command: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
     
   - name: Update Linux 
     command: apt update
    
   - name: Install Docker-ce
     command: apt install docker-ce docker-ce-cli containerd.io 

   - name: Copy file
     src: docker-compose.yml
     dest: /etc/
     owner: root
     group: root
     mode: '0777'

   - name: Create and start services Docker-compose start
     community.docker.docker_compose:
     project_src: flask
     register: output
 
   - ansible.builtin.debug:
     var: output

